#!/usr/bin/env node
/*
 * Build: src/ → dist/
 *
 *   dist/ghl/00-styles.css                      all the CSS, for GHL's Custom CSS box
 *   dist/ghl/00-head.html                       font link, for GHL's Tracking Code header
 *   dist/ghl/01-hero.html ... 04-reviews.html   paste-ready sections (JS and images inlined)
 *   dist/landing-page.html                      the whole page as one self-contained file
 *   dist/preview.html                           same page + a mock GHL form, for local testing
 *
 * Inlining rules (applied to src/sections/*.html):
 *   <script src="scripts/x.js"></script>         →  <script>…</script>
 *   src="images/x.webp" / url('images/x.webp')   →  base64 data URI
 *
 * Usage: node build.js   (no dependencies)
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const GHL = path.join(DIST, 'ghl');

const MIME = { '.webp': 'image/webp', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml' };

// Where each generated file goes in GoHighLevel (shown in its banner comment).
const PASTE_INTO = {
  '00-styles.css': 'Funnel step → Settings → Custom CSS',
  '00-head.html': 'Funnel step → Settings → Tracking Code → HEADER',
  '01-hero.html': 'Section 1 → Custom Code element',
  '02-quiz.html': 'Section 2 → Custom Code element',
  '03-before-after.html': 'Section 3 → Custom Code element',
  '04-reviews.html': 'Section 4 → Custom Code element',
};

const read = (p) => fs.readFileSync(p, 'utf8');

function inline(html) {
  return html
    .replace(/<script src="(scripts\/[^"]+)"><\/script>/g,
      (_, file) => `<script>\n${read(path.join(SRC, file)).trimEnd()}\n</script>`)
    .replace(/(src="|url\(')(images\/[^"')]+)("|'\))/g, (_, open, file, close) => {
      const abs = path.join(SRC, file);
      const mime = MIME[path.extname(abs)];
      if (!mime) throw new Error(`Unsupported image type: ${file}`);
      return `${open}data:${mime};base64,${fs.readFileSync(abs).toString('base64')}${close}`;
    });
}

function banner(name) {
  const text = `GENERATED by build.js from src/. Do not edit this file; edit src/ and run "node build.js".\n` +
               `   Paste into GHL: ${PASTE_INTO[name]}`;
  return name.endsWith('.css') ? `/* ${text} */\n` : `<!-- ${text} -->\n`;
}

function page({ withMock }) {
  const sections = fs.readdirSync(GHL).filter((f) => !f.startsWith('00-')).sort();
  return [
    '<!doctype html>',
    '<html lang="en-GB">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Free Driveway Quote + 10% Off | North Bound Surfacing</title>',
    '<meta name="description" content="Resin, tarmac, block paving, porcelain and artificial turf across Greater Manchester &amp; Cheshire. Get your free quote in 30 seconds with 10% off.">',
    '<style>html,body{margin:0;padding:0;background:#0F0F0F}</style>',
    read(path.join(GHL, '00-head.html')),
    `<style>\n${read(path.join(GHL, '00-styles.css'))}</style>`,
    '</head>',
    '<body>',
    withMock ? read(path.join(ROOT, 'tests/fixtures/mock-ghl-form.html')) : '',
    ...sections.map((f) => read(path.join(GHL, f))),
    '</body>',
    '</html>',
    '',
  ].join('\n');
}

function write(file, content) {
  fs.writeFileSync(file, content);
  console.log(`${path.relative(ROOT, file).padEnd(34)} ${String(Math.round(content.length / 1024)).padStart(4)} KB`);
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(GHL, { recursive: true });

write(path.join(GHL, '00-styles.css'), banner('00-styles.css') + read(path.join(SRC, 'styles/main.css')));
write(path.join(GHL, '00-head.html'), banner('00-head.html') + read(path.join(SRC, 'head.html')));
for (const name of fs.readdirSync(path.join(SRC, 'sections')).sort()) {
  if (!PASTE_INTO[name]) throw new Error(`Add ${name} to PASTE_INTO in build.js`);
  write(path.join(GHL, name), banner(name) + inline(read(path.join(SRC, 'sections', name))));
}
write(path.join(DIST, 'landing-page.html'), page({ withMock: false }));
write(path.join(DIST, 'preview.html'), page({ withMock: true }));
